import { StyleSheet } from 'react-native';
import type { Theme } from '../contexts/ThemeContext';

export const globalStyles = StyleSheet.create({
  screen: { flex: 1, padding: 16 },
  screenNoPadding: { flex: 1 },
  centeredScreen: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16 },
  container: { flex: 1 },
  content: { padding: 16, paddingBottom: 40 },
  list: { padding: 16, paddingBottom: 100 },
  empty: { alignItems: 'center', paddingVertical: 60, paddingHorizontal: 24 },
  emptyIcon: { fontSize: 56, marginBottom: 16 },
  emptyTitle: { fontSize: 18, fontWeight: '700', marginBottom: 8, textAlign: 'center' },
  emptySub: { fontSize: 14, textAlign: 'center', lineHeight: 20 },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  fabText: { color: '#fff', fontSize: 30, fontWeight: '600', lineHeight: 32 },
  card: { borderRadius: 14, padding: 16, borderWidth: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 8 },
  titleSmall: { fontSize: 18, fontWeight: '600', textAlign: 'center', marginBottom: 16 },
  subtitle: { fontSize: 16, lineHeight: 22 },
  format: { fontSize: 13, marginTop: 4 },
  label: { fontSize: 14, marginBottom: 8 },
  input: { borderRadius: 12, borderWidth: 1, padding: 14, fontSize: 16 },
  textarea: { minHeight: 80, textAlignVertical: 'top' },
  errorText: { fontSize: 12, marginTop: 4 },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowSpaceBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  row2: { flexDirection: 'row', gap: 12 },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 22, marginBottom: 8 },
  sectionTitle: { fontSize: 16, fontWeight: '700' },
  section: { marginBottom: 24 },
  formatRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  formatChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1 },
  formatText: { fontSize: 13 },
  schedulesList: { marginTop: 12, gap: 6 },
  scheduleBlock: { borderRadius: 12, padding: 14, borderWidth: 1, marginBottom: 12 },
  scheduleTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  timeBtn: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8 },
  timeValue: { fontSize: 22, fontWeight: '700', fontVariant: ['tabular-nums'] },
  removeBtn: { padding: 6 },
  miniLabel: { fontSize: 12, marginBottom: 6, marginTop: 4 },
  saveBtn: { marginTop: 24, paddingVertical: 16, borderRadius: 12, alignItems: 'center' },
  saveBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  name: { fontSize: 24, fontWeight: '700' },
  dosage: { fontSize: 16, fontWeight: '600', marginTop: 4 },
  meta: { fontSize: 14, marginTop: 4 },
  divider: { height: 1, backgroundColor: '#00000010', marginVertical: 14 },
  notes: { fontSize: 14, lineHeight: 20 },
  scheduleCard: { borderRadius: 12, padding: 14, borderWidth: 1, marginBottom: 10 },
  scheduleTime: { fontSize: 20, fontWeight: '700', fontVariant: ['tabular-nums'] },
  scheduleDays: { fontSize: 13, marginTop: 4, lineHeight: 18 },
  actions: { marginTop: 28, gap: 12 },
  btn: { paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  btnDanger: { backgroundColor: 'transparent', borderWidth: 1.5 },
  btnText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  scheduleRow: { flexDirection: 'row', alignItems: 'center', padding: 8, borderRadius: 8, gap: 10 },
  timeText: { fontSize: 15, fontWeight: '700', fontVariant: ['tabular-nums'], minWidth: 52 },
  daysText: { fontSize: 12, flex: 1 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 24 },
  box: { borderRadius: 16, padding: 24 },
  display: { alignItems: 'center', marginVertical: 16 },
  time: { fontSize: 56, fontWeight: '700', fontVariant: ['tabular-nums'] },
  controls: { flexDirection: 'row', justifyContent: 'space-around', marginVertical: 16 },
  col: { alignItems: 'center' },
  btnSmall: { padding: 12 },
  btnTextSmall: { fontSize: 22, fontWeight: '600' },
  actionBtn: { flex: 1, padding: 14, borderRadius: 10, alignItems: 'center', borderWidth: 1 },
  day: { flex: 1, aspectRatio: 1, borderRadius: 999, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5 },
});

export const themedGlobalStyles = (theme: Theme) =>
  StyleSheet.create({
    screenBackground: { flex: 1, backgroundColor: theme.colors.background },
    cardSurface: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderWidth: 1 },
    textPrimary: { color: theme.colors.text },
    textSecondary: { color: theme.colors.textSecondary },
    buttonPrimary: { backgroundColor: theme.colors.primary },
  });
